/* eslint-disable */
// Full service catalog — shared by Services overview, detail pages,
// home grid, footer, etc. Single source of truth.

window.SERVICES_DATA = [
  {
    id: "drone",
    num: "01",
    label: "Drone Aerial",
    tag: "FAA · PART 107",
    title: "Aerial proof of work. Weekly cadence available.",
    intro: "Aerial work for businesses that need visual proof their job is on schedule, their land is mapped, their venue looks good from 400 feet up. Part 107 licensed for commercial use across Wyoming.",
    body: "Construction progress, real estate, events, tourism. Edited 4K stills and clips back inside 48 hours. Files staged for MLS, broker socials, project pages, or dispute documentation.",
    bullets: [
      "Real estate exteriors + aerials",
      "Construction weekly progress shoots",
      "Event venue + crowd cover",
      "Tourism + destination footage",
    ],
    deliverables: [
      { name: "Drone Photo Session",    desc: "8–12 edited aerial stills · 30 min on-site · 24 hr delivery · $225" },
      { name: "Photo + Video Combo",     desc: "Stills + 30–60s edited reel from same flight · $425" },
      { name: "Construction Retainer",   desc: "2 visits/mo · photos + reel each · 3-mo minimum · $550/mo" },
      { name: "Half-Day Aerial",         desc: "Up to 4 hrs · Multiple locations · Travel within 25 mi · $650" },
      { name: "Event Aerial",            desc: "Per hour · 2 hr minimum · Weddings, festivals · $200/hr" },
    ],
    process: [
      ["Brief",       "10 min call. Share address, scope, deliverables."],
      ["Permit",      "Verify airspace + LAANC authorization where needed."],
      ["Fly",         "On site 60–90 min. I check weather + light window with you."],
      ["Deliver",     "Edited files back in 48 hours via shared drive."],
    ],
    pricing: [
      { tier: "Drone Photo",         price: "$225",   sub: "per session",   features: ["8–12 edited aerial stills", "30 min on-site", "24 hr delivery", "Part 107 covered"] },
      { tier: "Photo + Video Combo", price: "$425",   sub: "per session",   features: ["Stills + 30–60s reel", "Music + color graded", "7 day video delivery", "Best value"], featured: true },
      { tier: "Construction Retainer", price: "$550", sub: "per month",     features: ["2 visits per month", "Photo + reel each visit", "3 month minimum", "Site progress archive"] },
    ],
    price: "From $225 per session",
    coord: "ALT · 400 ft AGL",
    icon: "icon-drone.png",
    faq: [
      ["Are you Part 107 licensed?", "Yes. Current FAA Part 107 commercial drone certificate. $1M liability cert provided on request for any commercial client."],
      ["What about LAANC airspace?",  "I file LAANC authorizations myself for any controlled airspace in Albany County."],
      ["Weather rules for drone?",    "Drone has hard limits: no flying in wind above 25 mph, no temps below 40°F, and absolutely no flying in rain or snow. Any of those and we reschedule — free of charge."],
      ["What about travel?",          "First 65 miles round-trip from Laramie included free. Beyond 65 mi, $0.70/mile."],
      ["Indoor drone work?",          "Yes — warehouses, gyms, large interiors. +20% for permissions and risk handling."],
    ],
  },

  {
    id: "real-estate",
    num: "02",
    label: "Real Estate Photo",
    tag: "24 HR · SQFT-TIERED",
    title: "MLS-ready listing media. Drone included. Twenty-four hours, every time.",
    intro: "Listing media built for the way buyers actually scroll: hero shot, exterior, interior flow, drone exterior baked into every package, twilight or video if you want it. Every interior shoot includes a CubiCasa floor plan — I'm a CubiCasa partner, so the floor plan ships with the photo package at no extra cost. Files back the next day. Re-shoot included if the listing relists.",
    body: "Five sqft tiers, four package levels. Drone exterior shots are included automatically in every photo tier. Cinema Walkthrough video, Matterport 3D tour, and CubiCasa floor plan bundle up into Showcase and Immersive packages. Files delivered staged for MLS, IDX, and broker social.",
    bullets: [
      "HDR photos · unlimited count, no cap",
      "Drone exterior · included on every tier",
      "CubiCasa floor plan · included with Immersive",
      "Cinema Walkthrough video · flat $215 add-on",
      "Matterport 3D tour · sqft-tiered",
      "24 hour photo turnaround, 7 day video",
      "Re-shoot 1–2 rooms $75, or whole listing if it relists",
    ],
    deliverables: [
      { name: "ESSENTIALS",     desc: "HDR photos + drone exterior · MLS-staged · 24 hr · From $195" },
      { name: "SHOWCASE",       desc: "Essentials + Cinema Walkthrough video · From $385" },
      { name: "SHOWCASE PRO",   desc: "Showcase + Matterport 3D Tour · From $585" },
      { name: "IMMERSIVE",      desc: "Showcase Pro + CubiCasa floor plan · Full luxury kit · From $650" },
    ],
    process: [
      ["Book",        "Address, MLS deadline, special requests."],
      ["Shoot",       "On-site 90 min for a typical home. Interior + exterior + drone."],
      ["Edit",        "Color, exposure, lens correction, vertical straightening."],
      ["Deliver",     "MLS JPEGs + raw archive in your inbox by next EOD."],
    ],
    pricing: [
      { tier: "ESSENTIALS",     price: "From $195",   sub: "per listing",    features: ["HDR photos + drone exterior", "Unlimited photo count", "MLS-staged delivery", "24 hr turnaround"] },
      { tier: "SHOWCASE",       price: "From $385",   sub: "per listing",    features: ["Everything in Essentials", "Cinema Walkthrough video", "7-day video delivery", "Music + color graded"], featured: true },
      { tier: "SHOWCASE PRO",   price: "From $585",   sub: "per listing",    features: ["Everything in Showcase", "Matterport 3D Tour", "Embed-ready link", "48–72 hr 3D processing"] },
      { tier: "IMMERSIVE",      price: "From $650",   sub: "per listing",    features: ["Everything in Showcase Pro", "CubiCasa floor plan", "Full luxury kit", "Pushes slow markets"] },
    ],
    price: "Essentials from $195",
    coord: "EXP · 1/125 · f/8 · ISO 400",
    icon: "icon-real-estate.png",
    faq: [
      ["How does sqft pricing work?", "Five tiers: Spark (≤2,500), Pulse (2.5–3.5k), Beacon (3.5–4.5k), Spotlight (4.5–5.5k), Apex (5,500+). Apex is quoted individually. Prices shown are starting from Spark."],
      ["What's the turnaround?",      "24 hours for photos, every tier. 7 days for Cinema Walkthrough video. 48–72 hr for Matterport. No rush fee available — editing is outsourced, turnaround is fixed."],
      ["Is the floor plan really included?", "With Immersive, yes. I'm a CubiCasa partner — first 2D scan per month is free in the US, so the floor plan ships with the Immersive package at no upcharge. Standalone CubiCasa add-on is $75 if you want it on a smaller package."],
      ["Do you re-shoot?",            "1–2 rooms is a flat $75. If the listing relists or you need 3+ rooms re-done, it's the original package price — covers the full visit + edits."],
      ["What about travel?",          "First 65 miles round-trip from Laramie included free. Beyond 65 mi, $0.70/mile. No surcharge for weekend shoots."],
      ["What if it's bad weather?",   "For photo and video, we'll try to accommodate snow or light rain as much as possible — but a reschedule may be in the books, at no charge to you. Any drone exterior follows the drone weather rules (no rain, no snow, no winds above 25 mph, no temps below 40°F)."],
    ],
  },

  {
    id: "360",
    num: "03",
    label: "360 / Immersive",
    tag: "MATTERPORT GRADE",
    title: "Virtual walkthroughs. Embed once, tour forever.",
    intro: "Buyers tour from anywhere. Brokers cut showings. Vendors get walkthroughs without traveling. A floor plan is generated automatically from the scan.",
    body: "For listings, venues, showrooms, offices. Buyers and renters tour from anywhere, brokers cut showings, vendors get walkthroughs without travel. Floor plan auto-generated from the scan.",
    bullets: [
      "Matterport-grade scan",
      "Embed-ready hosted link",
      "Floor plan generated automatically",
      "48 hour delivery",
      "Mobile and VR compatible",
      "Owner can self-host or hand off",
    ],
    deliverables: [
      { name: "Residential Matterport",  desc: "Up to 3,500 sqft · Floor plan included with scan · 48–72 hr · From $225" },
      { name: "Commercial Google 360",   desc: "Google Street View Trusted for storefronts · 5–18 panoramas · From $295" },
      { name: "Re-scan existing tour",   desc: "Refresh after remodel or rebrand · $175" },
      { name: "CubiCasa floor plan",     desc: "Standalone 2D floor plan · 24 hr from scan · $75" },
    ],
    process: [
      ["Brief",       "Square footage, floor count, scan day."],
      ["Scan",        "On-site with the Matterport rig. Markers placed for every room."],
      ["Process",     "Auto-stitch + manual cleanup + floor plan extraction."],
      ["Deliver",     "Hosted embed URL + floor plan PDF + raw scan archive."],
    ],
    pricing: [
      { tier: "Matterport · Residential",  price: "From $225",  sub: "per listing",    features: ["Up to 3,500 sqft", "Embed-ready link", "Floor plan included with scan", "48–72 hr delivery"] },
      { tier: "Google 360 · Storefront",   price: "From $295",  sub: "per business",   features: ["Under 1,500 sqft", "5–8 panoramas", "Lives on Google Maps forever", "Exterior-only — no floor plan"], featured: true },
      { tier: "Google 360 · Medium",       price: "$450",        sub: "per business",   features: ["1,500–3,000 sqft", "8–12 panoramas", "Restaurants, retail, gyms", "Massive local SEO lift"] },
      { tier: "CubiCasa floor plan only",  price: "$75",          sub: "flat",             features: ["2D basic floor plan", "24 hr from scan", "PDF + DWG export", "No interactive tour"] },
    ],
    price: "From $225 per scan",
    coord: "POI · 360.00°",
    icon: "icon-360.png",
    faq: [
      ["Matterport vs Google 360 — which one do I need?", "Matterport is for residential listings: buyers tour from anywhere, embedded on MLS/IDX. Google Street View Trusted is for commercial storefronts: lives on Google Maps forever, big local SEO lift, no recurring hosting."],
      ["What hardware do you use?", "Matterport-grade 360 rig for residential. Google-certified workflow for Street View Trusted scans on commercial."],
      ["Can buyers tour on phones?", "Yes. The hosted tour works on mobile, desktop, and VR headsets."],
      ["Do I own the scan?",         "You own the deliverable. I host the embed for the listing window; archives are yours forever."],
      ["Is the floor plan included?", "With the Matterport residential scan, yes — the floor plan comes with the scan automatically. Exterior-only Google 360 storefront scans do not include a floor plan. Standalone CubiCasa floor plan is $75 if you need one without a tour."],
      ["Weather rules for 360 scans?", "360 tours absolutely cannot be exposed to snow or rain. Interior scans need a dry, clean walkthrough; exterior storefront scans get rescheduled if conditions are wet or icy — free of charge."],
    ],
  },

  {
    id: "brand",
    num: "04",
    label: "Brand",
    tag: "AUDIT + REFRESH + BUILD",
    title: "Logo, identity, audit, refresh. Whatever the brand needs.",
    intro: "Most small businesses end up with a logo from 2014 and a wordmark from a free template. I fix that. Brand audits with honest fix lists. Logo refreshes. New identities built from scratch. Full brand kits when you need everything — colors, type, logo, social templates, voice rules.",
    body: "Six-tier service line covering everything from a 30-minute walkthrough of what's broken to a full brand kit handoff. Pick the level you need.",
    bullets: [
      "30-min audit · PDF fix list · No upsell",
      "Logo refresh · Evolve what works, drop what doesn't",
      "New logo build · Wordmark + monogram + marks",
      "Full brand kit · Colors, type, logos, voice rules",
      "Social templates · IG story + post + highlight icons",
      "Visual identity system · Reusable across every surface",
    ],
    deliverables: [
      { name: "Brand Audit",      desc: "30 min walkthrough · PDF fix list · Phone tap check · Lighthouse pass" },
      { name: "Logo Refresh",     desc: "Evolve an existing mark · Wordmark + 1 secondary · 2 rounds revisions" },
      { name: "New Logo Build",   desc: "From scratch · Primary + monogram + favicon · Style exploration round" },
      { name: "Full Brand Kit",   desc: "Logo + color + type + voice + social templates · Hand off as folder" },
      { name: "Social Templates", desc: "6 story templates · 10 highlight icons · Editable in Canva" },
      { name: "Naming + voice",   desc: "Name exploration · Voice doc · Tagline + bio variants" },
    ],
    process: [
      ["Audit",       "I look at your existing brand (or absence of one). Honest assessment in 30 min."],
      ["Direction",   "Style exploration. 2–3 directions. You pick one. Or none — that's also fine."],
      ["Build",       "Final logo, full kit, or refresh. Two rounds of revision included."],
      ["Hand off",    "Editable source files + PDF guidelines + asset folder. You own everything."],
    ],
    pricing: [
      { tier: "Brand Audit",       price: "Free",      sub: "no upsell",       features: ["Google Biz, FB, IG review", "Website + logo review", "PDF fix list", "Hire me for the fixes — or don't"] },
      { tier: "Logo Refresh",      price: "$250",     sub: "flat",            features: ["Evolve existing mark", "3 concepts, 2 revisions", "2 file formats", "Light + dark variants"] },
      { tier: "New Logo Build",    price: "$450",     sub: "flat",            features: ["From scratch · 3 concepts", "Full file package", "Light + dark variants", "2 rounds of revisions"] },
      { tier: "Full Brand Kit",    price: "$1,100",   sub: "flat",            features: ["Logo + color + type", "6 social templates", "Business card design", "Voice + tone doc"], featured: true },
      { tier: "Brand Kit Lite",    price: "$600",     sub: "flat",            features: ["Logo + 2 colors + 1 font", "2 social templates", "Starter kit for new agents", "Faster turnaround"] },
      { tier: "Google Biz Profile", price: "$150",    sub: "flat",            features: ["Claim + verify + optimize", "10 photos uploaded", "Big SEO win for realtors", "Cross-sells with audit"] },
    ],
    price: "Audit · Free",
    coord: "SCAN + REFRESH + BUILD",
    icon: "icon-brand.png",
    faq: [
      ["I just need an audit, not a redesign.",      "Perfect. The audit is free. PDF fix list, no upsell. Hire someone else for the fixes — I won't follow up."],
      ["My logo is fine, but my brand is messy.",     "That's the refresh tier. We keep what works (the mark), fix what doesn't (colors, type, voice consistency)."],
      ["Can you do the website too?",                  "Yes — see /services/web-build. Most brand kit clients add a site build."],
    ],
  },

  {
    id: "web-build",
    num: "05",
    label: "Web Build",
    tag: "14 DAYS · FLAT FEE",
    title: "Built in fourteen days. You own the domain.",
        intro: "A real website. Mobile-first. Lead capture wired to your inbox. Hosted somewhere you can leave anytime. Flat fee, no hourly drift. The build takes about two weeks — going live depends on how fast we work through your revisions.",
    body: "Mobile-first website built on Framer or your CMS of choice. Real copy, real photos, lead capture wired straight to your inbox. Two rounds of revisions and a 30-day warranty on bugs.",
    bullets: [
      "Mobile-first responsive build",
      "Domain registration + hosting setup",
      "Lead form to your inbox",
      "Real copy + real photos",
      "Two rounds of revisions",
      "30 day bug warranty after launch",
    ],
    deliverables: [
      { name: "Single page",     desc: "One-page marketing site · Bio + services + contact" },
      { name: "Multi-page site", desc: "5 pages · Home, services, work, about, contact · Lead form wired" },
      { name: "E-commerce",      desc: "Up to 50 products · Stripe or Shopify · Inventory hand-off" },
      { name: "Property site",   desc: "Single-listing site · Photo gallery + virtual tour + lead form" },
    ],
    process: [
      ["Brief",       "30 min call. Sitemap, copy outline, photo audit."],
      ["Build",       "Wireframe → design → build. You see progress every Friday."],
      ["Polish",      "Two rounds of revisions. Performance + SEO + accessibility pass."],
      ["Launch",      "Domain + hosting transfer. 30 day bug warranty starts."],
    ],
    pricing: [
      { tier: "Landing Page",    price: "$600",    sub: "flat",   features: ["Single page", "Mobile responsive", "Contact form", "2 week turnaround"] },
      { tier: "Starter Site",    price: "$1,250",  sub: "flat",   features: ["3–5 pages", "Home, About, Services, Contact", "Basic SEO setup", "3–4 week turnaround"], featured: true },
      { tier: "Pro Site",        price: "$2,200",  sub: "flat",   features: ["5–8 pages + blog", "Lead capture + SEO", "IDX optional (real estate)", "4–6 week turnaround"] },
      { tier: "Site Refresh",    price: "$850",    sub: "flat",   features: ["Existing site redesign", "Same content, new design", "Faster than new build", "Same hosting"] },
      { tier: "Maintenance",     price: "$65",      sub: "per month", features: ["Up to 2 hrs edits/mo", "Backups + security", "Monthly recurring", "Cancel anytime"] },
    ],
    price: "From $600 flat",
    coord: "PERF · LH 95+",
    icon: "icon-web-build.png",
    faq: [
      ["Where does the site live?",       "Framer, Webflow, or a static host. You pick — domain stays in your account."],
      ["Can I update it myself?",          "Yes. Every build hands off with editable CMS access. I leave a loom walkthrough."],
      ["What about SEO?",                   "Built-in: meta tags, schema, sitemap, Lighthouse 95+. SEO content writing is a separate engagement."],
    ],
  },

  {
    id: "social-plan",
    num: "06",
    label: "Social Plan",
    tag: "MONTHLY RETAINER",
    title: "Thirty day calendar. You post it. I plan it.",
    intro: "Strategy and content calendar mapped to your services and verticals. I plan, write captions, recommend platforms — you press post. Monthly retainer with quarterly check-ins.",
    body: "Strategy and content calendar mapped to your services and verticals. Monthly retainer with quarterly check-ins. I plan, write captions, recommend platforms — you press post.",
    bullets: [
      "30 day rolling calendar",
      "Caption templates + variants",
      "Platform recommendations",
      "Service rotation across the month",
      "Monthly performance review",
      "Quarterly strategy check-in",
    ],
    deliverables: [
      { name: "30 day calendar",      desc: "Notion or Google Sheet · Post type, caption, hashtags, platform" },
      { name: "Caption library",      desc: "20+ caption templates · Customizable per service line" },
      { name: "Platform strategy",    desc: "Where to post what · Cadence recommendation · Best-time analysis" },
      { name: "Performance review",   desc: "Monthly call · What worked, what didn't · Next month's pivot" },
    ],
    process: [
      ["Audit",       "Look at last 90 days of posts. What's getting traction. What's noise."],
      ["Plan",        "Build the rolling 30-day calendar. Service rotation, post type mix, hashtag set."],
      ["Hand off",    "You get the calendar in Notion/Sheets. Captions written. Hashtags set."],
      ["Review",      "Monthly call to look at numbers and pivot. Quarterly deeper strategy reset."],
    ],
    pricing: [
      { tier: "Calendar Only",      price: "$175",    sub: "per month",   features: ["30 day rolling calendar", "Captions + hashtags", "You hit post", "Lowest commitment"] },
      { tier: "Starter Social",     price: "$400",    sub: "per month",   features: ["1 platform", "8–10 posts/mo, scheduled", "I post for you", "3 month minimum"] },
      { tier: "Pro Social",         price: "$650",    sub: "per month",   features: ["2 platforms", "12–15 posts/mo", "Light engagement", "Sweet spot for active agents"], featured: true },
      { tier: "Premium Social",     price: "$950",    sub: "per month",   features: ["2–3 platforms", "18–22 posts/mo", "Full engagement", "For top producers + teams"] },
      { tier: "Template Pack",      price: "$200",    sub: "one-time",     features: ["10 branded Canva templates", "Editable in Canva", "One-time purchase", "Pairs with any plan"] },
    ],
    price: "From $175 / month",
    coord: "CAL · 30 / 30",
    icon: "icon-social-plan.png",
    faq: [
      ["Do you post for me?",            "The base plan is strategy only — you hit post. Upgrade to Plan + Content if you want me to also produce + schedule."],
      ["Which platforms?",                "Instagram, Facebook, LinkedIn, TikTok, Google Business. I'll recommend a focused 2-platform mix based on your verticals."],
      ["Can I cancel?",                   "Yes, anytime. Month-to-month, no annual contract."],
    ],
  },
];
